server:
  port: 9090

spring:
  application:
    name: spring-config-server
  cloud:
    config:
      server:
        git:
          refreshRate: 60
          uri: https://github.com/jcsw/spring-config-properties
